main page styles refactored
jekabolt/grbpwr.com pull request #160
Opened 2024-12-23 19:39 UTC by 0101oak

2024-12-24 16:43 UTC, dogfrogfog requested changes
пофикси прото и комменты и посмотрю еще раз

2024-12-24 16:43 UTC, dogfrogfog commented on src/components/navigation-layout.tsx
> +      <div className="w-full lg:w-full">{children}</div>
w-full lg:w-full - тоже самое что w-full

2024-12-24 16:43 UTC, dogfrogfog commented on src/components/navigation-layout.tsx
> +    <div className="relative min-h-screen bg-bgColor pb-14 lg:pb-0">
проверь чтобы лэйаут был с отступами как ожидается на других страницах

тут ты убираешь отступ и это может поломать другие страницы

2024-12-24 16:43 UTC, dogfrogfog commented on src/app/_components/main-ads.tsx
> +    <div className="relative h-screen w-full md:-mt-20 md:h-full ">
без -mt-20 надо....почини прото чтобы тут превью ссылка зарпаботало и я смогу посоветовать что-то

2024-12-24 16:43 UTC, dogfrogfog commented on src/app/_components/main-ads.tsx
> +      <div className="h-screen md:h-[800px]">
разве screen не должно быть везде, зачем для планшета и десктопа ограничивать?

2024-12-25 14:14 UTC, 0101oak commented on src/components/navigation-layout.tsx
> +      <div className="w-full lg:w-full">{children}</div>
fixed

2024-12-25 14:14 UTC, 0101oak commented on src/components/navigation-layout.tsx
> +    <div className="relative min-h-screen bg-bgColor pb-14 lg:pb-0">
fixed

2024-12-25 14:15 UTC, 0101oak commented on src/app/_components/main-ads.tsx
> +    <div className="relative h-screen w-full md:-mt-20 md:h-full ">
fixed

2024-12-25 14:15 UTC, 0101oak commented on src/app/_components/main-ads.tsx
> +      <div className="h-screen md:h-[800px]">
fixed

2024-12-26 12:59 UTC, dogfrogfog approved these changes

2024-12-26 12:59 UTC, dogfrogfog commented on src/app/_components/main-ads.tsx
> +      <div className="absolute inset-0 z-10 flex h-screen items-center">
😻

2024-12-26 12:59 UTC, merged